name: build(dev)

on:  
  pull_request:
    branches: [deploy-dev, main]

jobs:
  build:
    name: build dev code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env: 
          CI: ""